language: java
install: true

env:
  global:
    - secure: WfqSSJPSSbb0LqHYJTrOndOqOrmH7DGSq6PTAErMEIC0b3IMryyxy1c5KGFS47Hr3pd9jCXYRXp8D8hYPWN1F0Oy1jRSkf4/53QFA8HdrGYe0KAc+wDOas/LPSSAAZFhqad+lKOYQKx0MGRuxAIg5l4C/ptdUK4HR2jTLsKcZ/MdmRrkGi4uKsvaa4upW+dpvOU8qncOSBgfzcBvdn51loeD69TxrH3Ug/zeJpsDF+pam9TX2+eukQgtdq7TNUA+ZjRxCBqJXl8bqT13EeeaBkUJt3ufc8PQQ8VwY+X0Xk781rEHg/qjMRxy9Bx/PIYBa+/dz412DHclY74mQvuN6grxr1gk5x/0ErC1q3YLXHaaWz6lF+5AwznNoS3DtyYvmSJhPzU9+O/ctvqGvzDvO5LCHPzX2gK7ckaH5RS9xVL6fgBVmoJED3FpyU/nC5uBD2I8leZc0POHIyTTcZ+NZYJJBX6YG17BGTlIDjyGb/xBWWSnsn5KtuoxFizrRzuJqDi4SM0Sl5KC/LjHgJPOjBspxC9SnLaXMhx6/JM1b13Fzd0ow9wx7q2TfPnldLbVVtydk6EjC+ogb64vtOlHDD6T0isGdLQ6M3SwwVAsAfe63mmvJAj4th5/oR4cQs6xWP3peeu3BGAEJ9r8oQDtoGagIDSWLSut9u4uPOJpvbc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: christian-draeger1@gmail.com
    - TRAVIS_REPO_SLUG: christian-draeger/jenkins-monitor
    - GIT_BRANCH: master

sudo: required

matrix:
  include:
  - jdk: oraclejdk8

before_install:
  - export TZ=Europe/Berlin
  - chmod +x changefile.sh
  - chmod +x deploy.sh

script:
  - mvn clean install
  - ./changefile.sh

before_deploy:
  - export JAR=$(ls target/jenkins-monitor-*.jar)
  - export DEB=$(ls target/jenkins-monitor-*.deb)
  - ./deploy.sh

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
    # how to create github token: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
  file:
    - ${JAR}
    - ${DEB}
  skip_cleanup: true
  on:
    repo: "${TRAVIS_REPO_SLUG}"
    tags: false
#    branches:
#      except:
#        - "/.v\d{2,4}/"
    branches:
       only:
         - "master"

notifications:
    email:
      on_success: change
      on_failure: change