language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
script:
- mvn clean install
- mvn clean package
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- export JAR=$(ls target/jenkins-monitor-*.jar)
- export DEB=$(ls target/jenkins-monitor-*.deb)
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$TAGPERM@github.com/christian-draeger/jenkins-monitor --tags
- ls -R
branches:
  except:
  - "/^*-v[0-9]/"
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  api_key:
    secure: hMiTQvknaQ1tGEBuO/UFdiygcVPU1ZEcEOc7v87NltvJngcbxce2Q6EXYl5kPfLqnXxBwZm5R2M0/cy07r9Cyzucxj1oq/5LupxZNn0GraENgOdwET34JYOa2+aoRNz68wC6dVtR81sPFjHfwgKXQ7qIdixeuaEDDepr5Vx2AwtvO2Vz9+60SODxtH8B0Gkv9uYZ8U3JF7N4aqxCNYzHYCb8Tx8l2nYGE58pLGUAgKjTju4oohHybVnlXaukNJClfwnNplgb5fkkNhbj50/Xv4g2csLofS1ijkgBXlPiEl+pqjRjZDfGIuYP+UB4kBrQSc6SozgsOgOgtpv0goX4nFaqK9lxLY7fX6q3VYkitmY5lI+dHLr6eQRBJ8DhVqSXUiLHgvTVulO/r32U0O4O0LpZgo4Xjb6ksRExQRTqNqL8TyOyou3+3JedcKZZoxqoB9vuRSB6Gzo1ZGnMq+Oh9xBANhQwxuvLw24r6BgC8Cx4Ask4NBt57dA3J9jtFspvfp/LnDLAIbcQtABjN2tAXNScv67PzqXGtexaNHILJ2reNZ3q92HeKywxfqPe0VCbO2Suk0rbQ4zSzTuNgh+MPoz3QuGtE8npYKYyouBOKiw/v+0DU2iw/7yCo9d0S/+g5gS2ukvzex9FQgzP4AlvnciGQOSl+p7dvvQcmuiGrzk=
  file:
      - $JAR
      - $DEB
env:
  global:
    secure: VqCYjEDrR7JiTim76oowHAvNOX37t5tU5K4WAhcyCW91grX6prUnIjk11zQSUwrM/XqT3/OyieA/Yeolxn6PYgRny865aSMFSkoS1tGoS4BVC3AUgow49s+1K9z378odZDMNoFXnWxoy/+tq6JDIZKzAPo03+hrvL4ru13aZgYjCAPkLN2y08aV3/BjK/xf1guqO1nKaFUj7S6/Rou41LHcEkknBv/IBBQI48ZATBl2DfHY81TF+3VIiWT0ifETy2P3kj/ZmzBVqEaD85AFm6pXa+r7LcSJDVxWYgkatkUbaMwLNvdQmJjw97Yp+jsWeVeeSsFZUnTigTR2CCJ60PBM4UAMdEkPAy3lOwm+YjVcGIirOrat07krnyg36ekjfqsk32ZICVifJvfGMvyU/CJUTzlGlcZfAMQZNcUgrXgDHN7VZ5E2mmKOhXc696V6+AXEMqdjMxfUuSE8h+M1VbF23DMNPLqEfkL4mS1X5WlrwMtHlDnsGlzVr6GwwlYnrtqNEe9SESGaQ+UdwAE4wcNldLlAY3jG5utuLrZ6NDtaLdaQBOPJwTJ1GLgBBxnLZxSqgUUCmlgWCptXx53+mYubzOxid/rZd8ok8CjhDPhoPxiqcnGXK4WELSC5QEJsUGsoH9mEKDyQnumEa3Ba3ObX/WPh4sX8Ps1oqEKv3//o=
