language: java
install: true

env:
  global:
    - secure: $GITPERM
    - GIT_NAME: Travis CI
    - GIT_EMAIL: christian-draeger1@gmail.com
    - TRAVIS_REPO_SLUG: christian-draeger/jenkins-monitor
    - GIT_BRANCH: master

sudo: required

matrix:
  include:
  - jdk: oraclejdk8

before_install:
  - export TZ=Europe/Berlin
  - chmod +x changefile.sh
  - chmod +x deploy.sh

script:
  - mvn clean install
  - ./changefile.sh

before_deploy:
  - export JAR=$(ls target/jenkins-monitor-*.jar)
  - export DEB=$(ls target/jenkins-monitor-*.deb)
  - ./deploy.sh

deploy:
  provider: releases
  api_key:
    secure: ${GITPERM}
  file:
    - ${JAR}
    - ${DEB}
  skip_cleanup: true
  on:
    repo: christian-draeger/jenkins-monitor
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"

notifications:
    email:
      on_success: change
      on_failure: change